# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ZYModuleExample' do
  inhibit_all_warnings!
  pod 'ZYModule'
#  pod 'MJRefresh'
#  pod 'FMDB'
#  pod 'LKDBHelper'
#  pod 'Masonry'
#  pod 'TMCache'
#  pod 'AFNetworking'
#  pod 'MBProgressHUD'
#  pod 'SVProgressHUD'

end
